### ISSUE TITLE
May 18th Goals

### ISSUE THREAD

**Issue by jarradbattaglia** [ayaigame/ayai-backend#95]
So this is our end of term list to do, gonna add everything here and then we will subtract what we don't want or cant do

**Backend (Primary)** 
- [x] Equipping and Unequipping Inventory
- [ ] Quest Tracking
- [x] Using/Dropping/Swapping Items
- [x] Status effects
- [ ] Handle Generated Maps
- [x] Experience When Killing Enemy
- [x] Fix how attack animations and sprite sheets are used on backend (Jarrad)
- [x] Create Leveling Up System (add experience to enemies, add levels and level growth)

**FrontEnd work (Primary)**
- [ ] Attack Animations with Swords and Weapons
- [ ] Fix Screen resizing (when bringing up menu, looks all screwy)
- [ ] People on Server Menu
- [x] Overworld music generated or assigned?
- [ ] Chat should display character name
- [x] No private chat? or group chat? thinking these may be useless to implement
- [x] Settings Screen (with all different key bindings)
- [x] Help Screen
- [x] Admin System (this is being reworked, no more quests, npcs, or rooms - these will be generated)
- [x] Sound Effects

**Both (Even work between FE and BE)**
- [ ] Using Actions on Action Bar (same as spells, essentially will be similar)
- [ ] Targeted Attacks

**Content Work**
- [x] Finish Character Selection
- [ ] New Sprites for main classes and main enemy subtypes

**AI Work (Backend)**
- [ ] Patrol AI
- [ ] Pathfinding AI
- [x] Director Spawn Enemies
- [ ] Spawn Points
- [x] Procedurally Generated Maps

**Senior Design Doc Work** 
- [x] Finish requirement  (not too hard, probably removing more than adding) (APRIL 29th)
- [x] Design doc  APRIL 29th
- [ ] Create presentation (could do during the next week) MAY 20th

**From Santi Meeting**
- [ ] Include installation instructions for server
- [x] Include a way for people to add their own content if they choose

So my main idea for this is to work on generating content.  So a user would login (yes still keeping that and we will spawn a new world and drop people in a designated level area that would match their style).  We would then spawn additional worlds and connect all rooms from here if need be (this may be hard and not doable).  I say we work on generating worlds and maps and make our project unique in that sense. Standard content created by us could not create enough to even make it look interesting .  

Users would keep their inventory, level, and equipment from server spawn to server spawn, but they would be moved to a different location (don't need to worry about saving rooms, etc).

We double down on Ai with the 4 people taking the class and you talk with Santi to figure different Ais and work with him in your class or after it to see how it could be easier to implement (I, Jarrad, cant do this because i don't know anything about Ai and im not working on it).  

Also since Rob and Ryan are in the AI class, Jarrad and Jared will take over the frontend and backend messages implementation (or the bulk of it).  

Our project is due May 13th, so we must start soon. Only about 6-7 weeks away

THIS IS APPROACH IS IN NO WAY FINAL, WOULD LIKE TO HAVE A DISCUSSION ABOUT IT. MOST OF THE COMMON MMO TASKS THOUGH ARE FINAL AND NEED TO BE COMPLETED. PLEASE HAVE A DISCUSSION BELOW, LETS TRY TO HAVE THIS PLAN SORTED OUT BY Tuesday the 25th.

**Comment by kurtwheeler** [comment]
Ok so I've been thinking and discussing the bare minimum we can have accomplished and still call this a game. All of these are listed above, but here they are all together:

**Tasks**
- [x] Experience/leveling
- [x] Shooting
- [ ] Procedurally generated quests
- [x] Procedurally generated maps
- [ ] Entity AI

Are there any other features that we need to be able to call this a game?

**Comment by timothyhahn** [comment]
![](http://i.imgur.com/RYq2YoF.gif)
